# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 424)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 418))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.registrationLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.registrationLabel.setFont(font)
        self.registrationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.registrationLabel.setObjectName("registrationLabel")
        self.verticalLayout.addWidget(self.registrationLabel)
        self.emptySpace = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.emptySpace.setText("")
        self.emptySpace.setObjectName("emptySpace")
        self.verticalLayout.addWidget(self.emptySpace)
        self.usernameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout.addWidget(self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout.addWidget(self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.paswordRetypeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.paswordRetypeLabel.setObjectName("paswordRetypeLabel")
        self.verticalLayout.addWidget(self.paswordRetypeLabel)
        self.paswordRetypeLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.paswordRetypeLineEdit.setObjectName("paswordRetypeLineEdit")
        self.verticalLayout.addWidget(self.paswordRetypeLineEdit)
        self.nameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.urlLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.urlLabel.setObjectName("urlLabel")
        self.verticalLayout.addWidget(self.urlLabel)
        self.urlLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.verticalLayout.addWidget(self.urlLineEdit)
        self.notesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.notesLabel.setObjectName("notesLabel")
        self.verticalLayout.addWidget(self.notesLabel)
        self.notesPlainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.notesPlainTextEdit.setObjectName("notesPlainTextEdit")
        self.verticalLayout.addWidget(self.notesPlainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registerPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.registerPushButton.setObjectName("registerPushButton")
        self.horizontalLayout.addWidget(self.registerPushButton)
        self.backPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.backPushButton.setObjectName("backPushButton")
        self.horizontalLayout.addWidget(self.backPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.registrationLabel.setText(_translate("Form", "Registracija"))
        self.usernameLabel.setText(_translate("Form", "Slapyvardis:"))
        self.passwordLabel.setText(_translate("Form", "Slaptažodis:"))
        self.paswordRetypeLabel.setText(_translate("Form", "Pakartotinis slaptažodis:"))
        self.nameLabel.setText(_translate("Form", "Pavadinimas:"))
        self.urlLabel.setText(_translate("Form", "URL:"))
        self.notesLabel.setText(_translate("Form", "Pastabos:"))
        self.registerPushButton.setText(_translate("Form", "Registruotis"))
        self.backPushButton.setText(_translate("Form", "Grįžti"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
