# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 295)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.registrationLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.registrationLabel.setFont(font)
        self.registrationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.registrationLabel.setObjectName("registrationLabel")
        self.verticalLayout.addWidget(self.registrationLabel)
        self.emptySpace = QtWidgets.QLabel(Form)
        self.emptySpace.setText("")
        self.emptySpace.setObjectName("emptySpace")
        self.verticalLayout.addWidget(self.emptySpace)
        self.usernameLabel = QtWidgets.QLabel(Form)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout.addWidget(self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(Form)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout.addWidget(self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(Form)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(Form)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.passwordRetypeLabel = QtWidgets.QLabel(Form)
        self.passwordRetypeLabel.setObjectName("passwordRetypeLabel")
        self.verticalLayout.addWidget(self.passwordRetypeLabel)
        self.passwordRetypeLineEdit = QtWidgets.QLineEdit(Form)
        self.passwordRetypeLineEdit.setObjectName("passwordRetypeLineEdit")
        self.verticalLayout.addWidget(self.passwordRetypeLineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registerPushButton = QtWidgets.QPushButton(Form)
        self.registerPushButton.setObjectName("registerPushButton")
        self.horizontalLayout.addWidget(self.registerPushButton)
        self.backPushButton = QtWidgets.QPushButton(Form)
        self.backPushButton.setObjectName("backPushButton")
        self.horizontalLayout.addWidget(self.backPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.registrationLabel.setText(_translate("Form", "Registracija"))
        self.usernameLabel.setText(_translate("Form", "Slapyvardis:"))
        self.passwordLabel.setText(_translate("Form", "Vartotojo slaptažodis:"))
        self.passwordRetypeLabel.setText(_translate("Form", "Pakartotinis vartotojo slaptažodis:"))
        self.registerPushButton.setText(_translate("Form", "Registruotis"))
        self.backPushButton.setText(_translate("Form", "Grįžti"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
